apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qnzngalqs-go 
  janus-idp.io/tekton: qnzngalqs-go
  backstage.io/kubernetes-id: qnzngalqs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qnzngalqs-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml